# Generated by Django 3.2.9 on 2021-11-16 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='reference',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
